services:
  backend:
    build:
      context: ../../backend
      dockerfile: ../docker/backend/Dockerfile

    image: biharibabu1/backend:1.0

    container_name: ledgerline-backend

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}

      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}

    ports:
      - "8080:8080"

    networks:
      - ledgerline-net