services:
  postgres:
    image: postgres:16-alpine

    container_name: ledgerline-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - ledgerline-net

volumes:
  postgres-data:

networks:
  ledgerline-net:
    driver: bridge