services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/frontend/Dockerfile

      args:
        VITE_API_URL: ${VITE_API_URL}

    image: biharibabu1/frontend:1.5

    container_name: ledgerline-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:80"

    networks:
      - ledgerline-net